spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: shingeki
    username: root 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
      name: Flight-Information
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka